/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotkavolterra;

import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author Tom
 */
public class GrapherFrame extends javax.swing.JFrame {

    LVPanel panel;
    /**
     * Creates new form GrapherFrame
     */
    public GrapherFrame(LVModel lv) { 
        initComponents();
        panel = new LVPanel(lv);
        add(panel);
        setSize(650,600);
        setVisible(true);
    }
    
    public GrapherFrame(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
